apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vajdwoxjg-go 
  janus-idp.io/tekton: vajdwoxjg-go
  backstage.io/kubernetes-id: vajdwoxjg-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vajdwoxjg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml